version: '3'

services:
  api-service:
    build: 
      context: ./api-service
      dockerfile: Dockerfile
    image: api-service
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/stock-api
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
      - serverless
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

  serverless:
    build: 
      context: ./stock-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - node-network

volumes:
  dbdata:

networks:
  developer:
  node-network:
    driver: bridge
